### ISSUE TITLE
Asynchronous

### ISSUE THREAD

**Issue by RichardVitaliz** [newbreedofgeek/react-stepzilla#107]
How does `isValidated()` handle asynchronous field validation? For example: I want to check if the user's email is already registered and display an error message appropriately. I do this by firing a `fetch()` to my back-end. If ever it would return anything (ergo: the async part) would decide if the component should go to the next step. The next button triggers `isValidated()` which contains `fetch()`. The issue I'm having now is, because `isValidated()` has to wait for the result of `fetch()` first, it can't determine whether it should go to the next step or not at the point of click. Please help. Not sure if I explained that well hahaha.

Also is it normal that I can't go to the next step when I use `isValidated()` as a callback function?

**Comment by danielsetreus** [comment]
`isValidated()` can also return a Promise. So I would do:

```
isValidated() {
     return new Promise((resolve, reject) => {
         fetch()
              .then(result => {
                    resolve()
              })
              .catch(error => {
                    // what ever
              }}
     })
}
```

This example of course only works if your `fetch()` method also returns a Promise. If not you could implement a callback argument and have `fetch()` run the callback when the request is completed. Then `resolve()` or `reject()` in the callback. I.e. 

```
isValidated() {
     return new Promise((resolve, reject) => {
         fetch((result) => {
                 if(result.someVar === true) resolve()
                 else reject()
         })
     })
}
```

**Comment by newbreedofgeek** [comment]
@danielsetreus thanks for your very clear explanation and appreciate your support in maintaining this project.

@RichardVitaliz you can have a look at this example code as well (@danielsetreus's code is also good)

https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Step5.js

Closing this, but reopen if you need more help.
