### ISSUE TITLE
Catch on Promises silent other errors

### ISSUE THREAD

**Issue by jorgecuesta** [newbreedofgeek/react-stepzilla#11]
Hi @newbreedofgeek me again. Yours .catch are silent other errors on components used as steps don't be raised. 
Try follow. Make a component with a development error, like use an undefined as function and should get it reproduced.

**Comment by newbreedofgeek** [comment]
I'm sorry, I don't follow. Can you please give me more detail.

**Comment by jorgecuesta** [comment]
When you build your component pass an array of steps:
```js
const steps = [{
name: '1',
component: <MyStepOne/>
}, {
name: '2',
component: <MyStepTwo/>
}];
<StepZilla steps={steps} ...props />
```
Right? ok now suppose that MyStepTwo have an error like use a dependency that not import before, or just use a function that is not defined, whatever. 

When render step one all be fine, but when try to go next step of course wrong coded component (MyStepTwo) raise an error and all those errors are catch by .catch() handler inside main.js at next() method on line: 184

**Comment by newbreedofgeek** [comment]
@jorgecuesta this was indeed a bug. The Promise was swallowing all errors as a React component loaded when you moved to a Step with an JS Error. I have used a known trick to pull naive errors out of the current execution stack and it seems to work well. 

It will now just throw the native error and break (as a JS app should break)

Give it a go and let me know if you see any other issues.

**Comment by jorgecuesta** [comment]
Thanks, I will let you know asap!
