### ISSUE TITLE
Suggestion: Change PropType of steps.name from string to object

### ISSUE THREAD

**Issue by tomtoxx** [newbreedofgeek/react-stepzilla#113]
Hi there,
I want to suggest changing the PropType from String to Object type.
My change request arises because I would like to use FontAwesome components for the navigation steps.
And I think more flexibility is a good think. 

``` 
const steps =
            [
                {name: <FontAwesomeIcon icon="book-open"/>, component: <Step1/>},
                {name: <FontAwesomeIcon icon="ruler-combined"/>, component: <Step2/>},
                {name: <FontAwesomeIcon icon="tint"/>, component: <Step3/>},
                {name: <FontAwesomeIcon icon="user"/>, component: <Step4/>},
                {name: <FontAwesomeIcon icon="check"/>, component: <Step5/>}
            ];
```
![grafik](https://user-images.githubusercontent.com/8841596/45470264-6888b080-b72d-11e8-8552-b75a16bc29e8.png)

**Comment by newbreedofgeek** [comment]
@tomtoxx thats a very cool looking implementation of StepZilla, I didn't expect FontAwesomeIcon to be used with 'name'

Have you tested it? Does it work for you as intended? Do you see any error in the console? (except for the propTypes error?)
