### ISSUE TITLE
How do you get the custom css to be used?

### ISSUE THREAD

**Issue by Frank-The-Tank** [newbreedofgeek/react-stepzilla#119]
I am able to use Step-Zilla but it looks weird as none of the css is recognized? I simply added react-zilla to my npm dependencies and did npm install

**Comment by newbreedofgeek** [comment]
@Frank-The-Tank the CSS styling is seperate from the functionality. But we provide a starting point. Just copy this CSS into your existing stylesheet and you will be good to go:

https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/css/main.css
