### ISSUE TITLE
jumpToStep issue

### ISSUE THREAD

**Issue by jorgecuesta** [newbreedofgeek/react-stepzilla#12]
Hi again... when use jumpToStep on lastStep (where apply nextTextOnFinalActionStep to footer button) step target of jumpToStep render same text as nextTextOnFinalActionStep.

It happen inclusive in your live demo example. You can see if click next button on step target will say Save in place of Next.

**Comment by jorgecuesta** [comment]
I find where the issue is... checkNavState method never restore next button text. Try doing jumpToStep(0) and will get on currentStep === 0 where if you already be on last step text of button is switched.

Maybe if you calculate text in place of save it on state this should not be necessary.

**Comment by newbreedofgeek** [comment]
Yep, I've added this as a bug.

**Comment by newbreedofgeek** [comment]
@jorgecuesta I've fixed this as well. Pls let me know if its works for you and if there is any regression. Thanks for your help in finding these bugs.
