### ISSUE TITLE
How can I get Current Step index from within a Child Step Comp?

### ISSUE THREAD

**Issue by illia108** [newbreedofgeek/react-stepzilla#124]
Hi.
Is it possible to get a current step number inside step component?
What I'd like to do is to hide Next button in some components and use `jumpToStep` function instead. In these components I have two radio buttons. So as far as a selection is made it should take a user to the next step.

So I came up with this:
1. hide navigation with css as @newbreedofgeek suggested in some issue
2. then use `jumpToStep(currentStep + 1)`

So is there access to so-called `currentStep`?

**Comment by newbreedofgeek** [comment]
@illia108 we could put in a static method to return this but would rather have more people request this feature before we update the core logic.

In the meantime.. there a hacky way to do this by reading the DOM rendered style, something like this:

```
let all = document.querySelectorAll('.progtrckr > li');
let currentStep = -1;

x.forEach((i, idx) => {
  if (i.className === 'progtrckr-doing') {
    currentStep = idx;
  }
});

console.log(currentStep);
````

Would that work? above code has not been tested... just a guide

**Comment by illia108** [comment]
Thank you @newbreedofgeek 
Yesterday I ended up with just passing a currentStep (actually nextStep) into the step component.
`{ name: 'Step 2', component: <StepTwoRoutine name={ this.state.name } onSelect={ this.onSelect } nextStep={ 2 } /> }`
