### ISSUE TITLE
step 4 displays empty content 

### ISSUE THREAD

**Issue by Khareem23** [newbreedofgeek/react-stepzilla#131]
My Step 4 is Plain not deplaying the page content but step 5 displays . is there a configuration i've to alter . immediate response would be appreciated Please

**Comment by brennondenny** [comment]
Can you post a snippet?

**Comment by Khareem23** [comment]
I later got it to work . Is stepzilla now working with Redux without issues ?

Awaiting your reply... Thank you

Sent from my iPhone

On Jan 18, 2019, at 7:47 PM, Brennon Denny <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you post a snippet?

**Comment by brennondenny** [comment]
Yes, actually using it with Redux in a project I'm working right now.

**Comment by Khareem23** [comment]
Oh nice work Bro . God bless you . I used stepzilla for an Enterprise Web App I just completed and I really enjoyed it . It makes my work faster and nice .

I can’t wait to see it working with redux

Sent from my iPhone

On Jan 18, 2019, at 8:24 PM, Brennon Denny <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, actually using it with Redux in a project I'm working right now.

**Comment by newbreedofgeek** [comment]
@brennondenny tnx for helping @Khareem23 

Also glad you have it working with redux... I'm working on a sample redux implementation now. Closing ticket.
