### ISSUE TITLE
Question: How to know if next button is clicked or previous button ? 

### ISSUE THREAD

**Issue by farazirfan47** [newbreedofgeek/react-stepzilla#132]
I want to do some customization like sending/stopping server call based on next or previous button click, but only If I am able to detect which button is clicked.
Is there anything else we can receive as parameter rather than step number in onStepChange function ?

**Comment by newbreedofgeek** [comment]
At this stage you can only use onStepChange function to get the step it changed to. You might be able to hoist a state option to the top... i.e the parent component that has <StepZilla> can have a custom state value to say if the step number went up or down, and the logic to change it... that way you know if next or previous was pressed. 

So the parent has something like this: (code not tested... just an idea)

```
state = {
    nextPressed: false,
    prevPressed: false,
    stepInView: -1
  }
   
   determineNextOrPrev = (step) => {
    if (step < this.state.stepInView) {
      this.setState({
        prevPressed: true,
        nextPressed: false,
        stepInView: step
      });
      } else {
      this.setState({
        prevPressed: false,
        nextPressed: true,
        stepInView: step
      });
    }
   }

   <Stepzilla steps=[
    {name: 'Step 1', component: <Step1 determineNextOrPrev=this.determineNextOrPrev />},
    ] />
```

Let me know if this works...

**Comment by newbreedofgeek** [comment]
Closing this for now.. pls reopen if needed.
