### ISSUE TITLE
Question - Show step titles in small screen

### ISSUE THREAD

**Issue by dsun29** [newbreedofgeek/react-stepzilla#14]
Stepzilla shows only step numbers (1, 2,3, etc,) and hide step titles in small screens. How can we make it still show step titles/texts?

**Comment by newbreedofgeek** [comment]
@dsun29 This is just a CSS setup. If you are using the default CSS you will notice here:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/css/main.css#L19

That the title is hidden for smaller screens.

You can overwrite that in your CSS to show the title and maybe reposition or rotate the labels.

It is difficult as your wont have much screen real estate but its up to you, as you control the CSS.

Hope that helps.

**Comment by dsun29** [comment]
It does help! Thank you for your info.
