### ISSUE TITLE
Navigating to steps based on a form's dropdown value

### ISSUE THREAD

**Issue by Priam123** [newbreedofgeek/react-stepzilla#141]
How to use the jumpToStep function on pressing the next button in stepzilla? Control needs to jump to a step based on a form's dropdown value. 
The example has links for jumpToStep but I want to link it to the **Next** button in StepZilla. Is it possible?

**Comment by zeel** [comment]
You can use `isValidated` method to check dropdown value and use `jumpToStep` method inside it.
