### ISSUE TITLE
What is step-progess css class? 

### ISSUE THREAD

**Issue by jagjitsingh700** [newbreedofgeek/react-stepzilla#143]
Hi,

I have seen in your documentation that this can be used in the application to use `react-stepzilla`:

 ```
<div className='step-progress'>
   <StepZilla steps={steps}/>
</div>
```

I am not fully sure if `step-progress` is `CSS` class coming as a part of the `react-stepzilla` npm package or this is a CSS class I have to create myself? (Just got confused as StepZilla component is rendered inside a div with a class).

**Comment by zeel** [comment]
@jagjitsingh700 It's just a class. It doesn't convey any purpose. There is no css attached to this class.
