### ISSUE TITLE
Update Bootstrap to v4.x.y

### ISSUE THREAD

**Issue by senakafdo** [newbreedofgeek/react-stepzilla#144]
Bootstrap v4 was released in January 2018, and it has a new and better structure compared to v3. A v5 would soon be available too. It would be best to start supporting the new versions of bootstrap alongside v3, or migrate to the newer version if possible.

**Comment by newbreedofgeek** [comment]
Thanks for the suggest @senakafdo a the core StepZilla component itself is unopinionated when it comes to styling libraries like bootstrap as you can see from the core code HTML:
 https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js

You must mean bootstrap as used in the example pages and test harness? I’m closing this as I don’t think it’s a core issue to StepZilla component itself - but let me know if you have any comments:issues
