### ISSUE TITLE
How i can get last step

### ISSUE THREAD

**Issue by AliSultanKhan** [newbreedofgeek/react-stepzilla#148]

**Comment by zeel** [comment]
@AliSultanKhan Can you clarify more. 

Do you want to navigate to the last step directly?
You can use jumpToStep prop passed to step component.

Thanks!

**Comment by nttoan26** [comment]
I think the question is how a step know which activeStep is now.

**Comment by zeel** [comment]
@nttoan26 @AliSultanKhan `onStepChange` gives index of step on which currently user is present as a function's argument. 

I guess You can use this argument to get last active step by subtracting 1.

Let me know if any further help is needed.
