### ISSUE TITLE
Accessing the typed in info

### ISSUE THREAD

**Issue by yarivShamash** [newbreedofgeek/react-stepzilla#159]
I am a junior developer and started using your library recently.
Hope it's not too much of a layman question..

**Description**
I am transferring a single page form to a step by step from using your library.
In the former code `e.target.elements` stored all the information from the form-elements after pressing the submit button, now it returns undefined.
How should I pull the submitted info?

**Comment by brennondenny** [comment]
If I'm understanding this right, you should be able to see all your data in the state/store.

**Comment by yarivShamash** [comment]
Thanks for the rapid response and apologies for my late one..

I tried passing 
```
  handleSubmit = async e => {
    e.preventDefault();
 console.dir(this.state);
  };
```
To the `<form onSubmit={this.handleSubmit}>` that wraps `<StepZilla preventEnterSubmission={true} steps={steps} />`
and got an empty state _after filling_ the form.
I also tried to ` console.dir(StepZilla.state)` but got `undefined`.

Since I might have not explained correctly I am trying again.
As described above, I was converting an HTML form to StepZilla and I want to send the information collected in StepZilla to a server but I don't know where it's stored and how to access it.
The former form used:
```
  handleSubmit = async e => {
    e.preventDefault();
    const formElements = e.target.elements; // Here the information was stored
// rest of the function goes here, it checks and sends the data
}
```
Looking forward to your replay :)

**Comment by brennondenny** [comment]
You should not be wrapping StepZilla inside a form.

You should be using the step components, you can create a submit function that handles the submit just be sure to pass it to the component.

You should be able to use `this.state` in your main file but in order to access it in the components you need to be passing it in props.

Let me know if that help or if you have any more questions.

**Comment by yarivShamash** [comment]
Thanks mate :)
I sorted it out by setting the input information to the parent state. All methods are there (the parent) as well and are passed as props to the children (the form steps).

**Comment by brennondenny** [comment]
Glad you got it working!
