### ISSUE TITLE
Impossible to get next/save button in the last step?

### ISSUE THREAD

**Issue by JimVercoelen** [newbreedofgeek/react-stepzilla#16]
Is it possible to have a next button in the last step?

If I look at the demo, 'step 4' has one, but I just cannot get the same result for some reason?

**Comment by newbreedofgeek** [comment]
@JimVercoelen usually the idea with a "wizard" tool like StepZilla is to collect data through a series steps and on the step before the last (Step 3 in the example), have the user "Review" their data and "Save" it. The last step is usually a "Thank You" message after saving to server is complete (like Step 4 in the example)

The final step is where the Wizard ends so there is no "next" step needed.

Why would you want a "Next" step on the last step and where would it go when clicked?

**Comment by JimVercoelen** [comment]
Ah that's to bad.

The purpose was to submit every thing on the last step and redirect to another part of the application.

Maybe if you'll get bored once, you can edit it ;-p, 
for me it was limited so I had to use something else.

**Comment by newbreedofgeek** [comment]
You can still do that using StepZilla, once your save was successful just redirect to your own Component in the componentDidMount() of the final StepZilla step.

e.g.

So in the example code as per here:
https://newbreedofgeek.github.io/react-stepzilla/

In Step4 which is the "Review" step, when you hit the "Save" button, it will go to Step5. In the Step5 component just tap into the componentDidMount() and redirect or mount your own Component. 

Best of luck...
