### ISSUE TITLE
[BUG] Navigation Bar is plain HTML (No customization)

### ISSUE THREAD

**Issue by rahulgrover-cn** [newbreedofgeek/react-stepzilla#160]
**Describe the bug**
The navigation bar shows only the step numbers. Though, clicking on them takes you to the desired step but it's not customised

**Expected behavior**
![image](https://user-images.githubusercontent.com/64029520/82373269-f9537b80-9a3a-11ea-96f9-f38e118bf36b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/64029520/82373005-8944f580-9a3a-11ea-83b6-45962d700867.png)

**Desktop (please complete the following information if applicable):**
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Additional context**
"dependencies": {
    "@emotion/core": "^10.0.27",
    "@emotion/styled": "^10.0.27",
    "@material-ui/core": "^4.9.0",
    "@material-ui/icons": "^4.5.1",
    "@mrblenny/react-flow-chart": "0.0.9",
    "ace-builds": "^1.4.8",
    "ajv": "^6.12.0",
    "bootstrap": "^4.4.1",
    "lodash": "^4.17.15",
    "prop-types": "^15.7.2",
    "query-string": "^6.10.1",
    "react": "^16.12.0",
    "react-ace": "^8.1.0",
    "react-dom": "^16.12.0",
    "react-icons": "^3.8.0",
    "react-jsonschema-form": "^1.8.1",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.4.0",
    "react-stepzilla": "^6.0.2",
    "react-toasts": "^3.0.6",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "semantic-ui-react": "^0.88.2"
  },

**Comment by scumah** [comment]
You need to add [this CSS](https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/css/main.css) for the progress bar to look like that.
