### ISSUE TITLE
Default styling not coming

### ISSUE THREAD

**Issue by rajatmadaan786** [newbreedofgeek/react-stepzilla#163]
When I am using "**react-stepzilla**", It's default styling not coming. Even I was not able to find like, Do I have to import any css file for the same.

Below are the attachments of, How it looks like at my side.

![secondStep](https://user-images.githubusercontent.com/60581494/95296718-e54bd180-0896-11eb-8f99-7e312e99fd64.PNG)

![firststep](https://user-images.githubusercontent.com/60581494/95296714-e3820e00-0896-11eb-9726-81a44e554e1a.PNG)

**Comment by brayden2544** [comment]
Having the same issue.

**Comment by rajatmadaan786** [comment]
@brayden2544 , I have fixed it by copying the main.css file from node_modules in my development folder.

**Comment by newbreedofgeek** [comment]
@rajatmadaan786 yes - that is the solution. Or get it from the github source. It’s basic CSS that you copy into your solution and update as needed
