### ISSUE TITLE
[BUG] progtrckr not being added on <li>

### ISSUE THREAD

**Issue by stevenarevalo** [newbreedofgeek/react-stepzilla#177]
**Describe the bug**
The progtrckr- class in `<li>` is not being added:
![image](https://user-images.githubusercontent.com/79937413/130695684-bac774ca-b85b-4319-83e6-5e51b58978a4.png)
And also the next button is not working. 

**To Reproduce**
1. I just imported the library in my React app and I also  imported the css styles  file

**Expected behavior**
It should show something like this (this is from the live example):
![image](https://user-images.githubusercontent.com/79937413/130695873-8396fa66-1889-4fc4-b398-c75adf38b6e8.png)

**Desktop (please complete the following information if applicable):**
 - OS: MacOs
 - Browser Chrome

**Comment by newbreedofgeek** [comment]
Hi @stevenarevalo - thanks for the detailed bug report.

This is a strange one as I cant repro it.

- Do you see any JS errors in the browser console? FYI this is where classnames for the Li's are created: https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js#L265
- Do your footer buttons have classes? as classes are set in a similar way to the Li :https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js#L325

**Comment by newbreedofgeek** [comment]
Closing this as there is no response and cant repro - reopen if its still an issue with more details
