### ISSUE TITLE
Steps styles are not correct when using 'startAtStep' prop

### ISSUE THREAD

**Issue by avivr** [newbreedofgeek/react-stepzilla#18]
When using startAtStep prop, the stepper looks like you are in the first step.
First step in 'in-progress' state, and all other steps seems to be in 'todo' state (style-wise, grey color).

Fixed by PR #17

**Comment by avivr** [comment]
Also applied to prev/next buttons state

**Comment by newbreedofgeek** [comment]
@avivr tnx for raising bug an issuing pull.

I will review and merge it in :)

**Comment by newbreedofgeek** [comment]
fixed thanks to PR #17
