### ISSUE TITLE
nextTextOnFinalActionStep misses the mark

### ISSUE THREAD

**Issue by younanjo** [newbreedofgeek/react-stepzilla#2]
When enabling nextTextOnFinalActionStep="Submit" the previous steps are also changed to "Submit" where they should have remained "Next".

**Comment by newbreedofgeek** [comment]
@younanjo let me check.

**Comment by newbreedofgeek** [comment]
@younanjo i've confirmed its NOT an issue and it works. I've updated the example app to show you how. Check out [ae7ee701cf09f8a95efb41078df37310d509f147].

Make sure you update to 1.9.1
