### ISSUE TITLE
When you only have 2 Steps, nextTextOnFinalActionStep does not work

### ISSUE THREAD

**Issue by newbreedofgeek** [newbreedofgeek/react-stepzilla#21]
You can only update the nextTextOnFinalActionStep if you have 3 or more steps. This is most probably a bug, but not a major issue as most people will have more than 2 steps.

**Comment by agent3bood** [comment]
check 
https://github.com/newbreedofgeek/react-stepzilla/pull/51

**Comment by newbreedofgeek** [comment]
Fixed in v4.6.0 via pull request #51 thanks to @agent3bood .

It's been tested but pease test and let us know if it has issues and we will reopen to investigate.
