### ISSUE TITLE
Custom buttons

### ISSUE THREAD

**Issue by darshan-raj** [newbreedofgeek/react-stepzilla#23]
Hi @newbreedofgeek is it possible to configure custom controls for the previous and next buttons?

**Comment by newbreedofgeek** [comment]
@darshan-raj unfortunately not.

They are standard buttons at this stage as you can see:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js#L305

May I know what kind of custom components do you want to use? and what's your use case? 

If it's a valid scenario then I can put this down as an enhancement or I may be able to suggest an alternative.

**Comment by patoaesteve** [comment]
Hi @newbreedofgeek , is it possible to change the text of the buttons? I'm from Latin America, and i need it in Spanish, with other legend. 

Thks!

**Comment by newbreedofgeek** [comment]
@patoaesteve This is a valid case. I have raised this as a new feature (#25) and am working on it today.

**Comment by newbreedofgeek** [comment]
@darshan-raj as I'm not heard from you on your use case. I'm closing this for now. You can reopen it if needed and provide some more detail on your use case. Tnx.

**Comment by newbreedofgeek** [comment]
@patoaesteve I've added this feature for you. Pls see #25 and test and let me know if it works. 

Remember you need to do a npm update to get the latest version (v4.4.4)
