### ISSUE TITLE
License

### ISSUE THREAD

**Issue by smattt** [newbreedofgeek/react-stepzilla#24]
Thank you for donating your time and talent to this project, I appreciate your efforts.

I've started using and modifying the code for a project and it's going well. However, I wasn't able to find the licensing terms for your code and I was wondering if you could please clarify what they are. I want to be sure that I'm not violating your license :)

Thank you for your help

**Comment by newbreedofgeek** [comment]
@smattt glad you enjoy this project.

It is under the ISC License 
- https://github.com/newbreedofgeek/react-stepzilla/blob/master/LICENSE.md

Best of luck with your projects.
