### ISSUE TITLE
passing Data

### ISSUE THREAD

**Issue by arifsohail** [newbreedofgeek/react-stepzilla#26]
how can i pass data from one step to another. can i use props.getStore(). to store and change the values.

**Comment by newbreedofgeek** [comment]
@arifsohail - It's up to you how you want to maintain state. There are multiple options like Redux, Flux etc or you can have your own custom store approach like what've shown in the example. i.e

In my main app file, I create a simple object store:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Example.js#L17-L20

I then have getStore and updateStore methods:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Example.js#L28-L37

I then pass these 2 methods to all the individual steps:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Example.js#L42

Now each step has access to props.getStore() and props.updateStore() to get and manipulate state.

You can see this in the example code by looking at the various steps and running the sample.

Hope that helps.

**Comment by arifsohail** [comment]
thanks a lot. i guess redux will work nicely
