### ISSUE TITLE
bootstrap classes is used but dependency not added in package.json

### ISSUE THREAD

**Issue by zeel** [newbreedofgeek/react-stepzilla#40]
<img width="1216" alt="screen shot 2017-05-08 at 12 03 35 pm" src="https://cloud.githubusercontent.com/assets/1536949/25792801/86f54dec-33e6-11e7-80c5-2dfea93f1317.png">
In the footer is using bootstrap btn classes, and it's not specified in the dependency. 

Ideally, it should not add bootstrap as a dependency but can add styles of the button only. 

Let me know if I can open pr to add styles of button, it would be great! :)

**Comment by newbreedofgeek** [comment]
@zeel Yes I agree with you. Bootstrap classes should NOT be baked into the core markup and should be an optional setting. Also don't think bootstrap should be a dependency.

I'm pretty sure it's only the footer buttons markup that has bootstrap classes.

Maybe we can pull out 2 more config settings:

// specify the next button text (if not given it defaults to "Next")
nextButtonCls: "btn btn-prev btn-primary btn-lg pull-left"

// specify the back button text (if not given it default to "Previous")
backButtonCls: "btn btn-next btn-primary btn-lg pull-right"

It will be great if you can open a PR! I would like more contributors as more people seem to be using StepZilla each day.

**Comment by zeel** [comment]
Thanks, @newbreedofgeek for the reply. 

sure I will give PR in some time.

**Comment by zeel** [comment]
opened pr

**Comment by agent3bood** [comment]
Is the PR going to be accepted? really need it.
 I can add test for it later.

**Comment by newbreedofgeek** [comment]
@agent3bood @zeel Tnx for the push, this slipped my radar.

But the tests are failing on this merge, due to the btn-classes being used to locate the buttons in the tests.

I can only get to this next week but if you can contribute to the PR and fix the tests I can accept it by tomorrow.

Thanks.

**Comment by newbreedofgeek** [comment]
@agent3bood @zeel one way around this to keep a fixed class for next/prev buttons (i.e. next and prev) and append the classes from nextButtonCls and backButtonCls if needed. This way the tests wont have to change too much and we can use the .next and .prev classes to locate the items in the test.

**Comment by agent3bood** [comment]
Keeping the bootstrap class may affect the style of the buttons. 
I say let the class be fully changable throught props and add id to the buttons and change the test. 
Id can be unique like 'react-step-zilla-next-btn'

**Comment by zeel** [comment]
@newbreedofgeek @agent3bood will do suggested by @agent3bood today. sorry didn't reply earlier and will run the tests this time.

**Comment by newbreedofgeek** [comment]
Agree with @agent3bood - this is the right way to do it. @zeel thanks for your contributions. Once you update and PR or raise now PR I will test and release.

**Comment by zeel** [comment]
@newbreedofgeek @agent3bood I have updated the pr with all test cases are passing.

**Comment by rubystar** [comment]
Hey, can we please get it merged? Thanks

**Comment by newbreedofgeek** [comment]
@rubystar @agent3bood Sorry for the delay in merging this. It has been done, tnx @zeel for the excellent work.
