### ISSUE TITLE
Wizard progress bar is not rendering

### ISSUE THREAD

**Issue by JinGuoGe** [newbreedofgeek/react-stepzilla#41]
Why progress bar is broken?
Perhaps is it related with other dependencies?

I am using following..

`"dependencies": {
    "canvas-gauges": "^2.1.0",
    "centrifuge": "^1.4.1",
    "classnames": "^2.2.5",
    "crypto-js": "^3.1.9-1",
    "express": "^4.14.0",
    "express-history-api-fallback": "^2.1.0",
    "fs": "0.0.1-security",
    "gulp-util": "^3.0.7",
    "history": "^2.1.2",
    "pubsub-js": "^1.5.3",
    "rc-tabs": "^7.1.0",
    "react": "^15.3.2",
    "react-addons-css-transition-group": "^15.3.2",
    "react-bootstrap": "^0.30.3",
    "react-day-picker": "^5.1.1",
    "react-dom": "^15.3.2",
    "react-dropzone": "^3.13.1",
    "react-router": "^3.0.0",
    "react-router-bootstrap": "^0.23.1",
    "react-select": "^1.0.0-rc.3",
    "react-stepzilla": "^4.5.0",
    "sha256": "^0.2.0",
    "webpack-dev-server": "^1.16.2"
  },
  "devDependencies": {
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "browser-sync": "^2.16.0",
    "connect-history-api-fallback": "^1.3.0",
    "css-loader": "^0.25.0",
    "del": "^2.2.2",
    "exports-loader": "^0.6.3",
    "file-loader": "^0.9.0",
    "gulp": "^3.9.1",
    "gulp-changed": "^1.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-cssnano": "^2.1.2",
    "gulp-expect-file": "0.0.7",
    "gulp-filter": "^4.0.0",
    "gulp-flatten": "^0.3.1",
    "gulp-html-prettify": "0.0.1",
    "gulp-if": "^2.0.1",
    "gulp-ignore": "^2.0.1",
    "gulp-jade": "^1.1.0",
    "gulp-jsvalidate": "^2.1.0",
    "gulp-less": "^3.1.0",
    "gulp-load-plugins": "^1.3.0",
    "gulp-rename": "^1.2.2",
    "gulp-rtlcss": "^1.0.0",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-sync": "^0.1.4",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "imports-loader": "^0.6.5",
    "marked": "^0.3.6",
    "modernizr-webpack-plugin": "^1.0.5",
    "react-hot-loader": "^3.0.0-beta.4",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.7.0",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-stream": "^3.2.0",
    "yargs": "^5.0.0"
  }`

![untitled](https://cloud.githubusercontent.com/assets/15504060/25794665/8760031c-3404-11e7-8540-8e93e8cc63f3.png)
Looking forward to be solved.
Thanks.

**Comment by newbreedofgeek** [comment]
@JinGuoGe 

Can you show me your StepZilla setup / config?

// disable or enable the steps UI navigation on top 
showSteps: true

// disable or enable onClick step jumping from the UI navigation on top
stepsNavigation: true

Both the above flags should NOT be false, by default it is true so make sure you have not set it to false.

Also make sure some CSS is not hiding it.

Or show me your config and I'll try and help.

**Comment by jeznag** [comment]
@JinGuoGe did you include the CSS? Looks like it's working fine, you're just not styling it.

```also if you want some default style, copy the source from src/css/main.css code into your project (the above look in the picture also requires bootstrap)```

**Comment by newbreedofgeek** [comment]
@jeznag tnx for following up and solving! Appreciate your help.

**Comment by cdesch** [comment]
Any to configure this with `react-strap ProgressBar` or `boostrap progressbar`
