### ISSUE TITLE
Do not show next button if you have only one step

### ISSUE THREAD

**Issue by agent3bood** [newbreedofgeek/react-stepzilla#42]
Do not show next button if you have only one step.

**Comment by agent3bood** [comment]
Here is what I understood how buttons showld be shown or not, correct me if wrong so I can work on this. 

Next button:
Show on all steps
Hide on last step only


Previous button:
Hide on first step
Show on all other steps
Hide on last step if configured so in props

Next button text:
Default is 'next'
If configured in props then do so
If the second defore last is configured to use different text then do so.

**Comment by newbreedofgeek** [comment]
@agent3bood Can I ask who you would like to use StepZilla if you only have 1 step? StepZilla only makes sense if you have more steps as it's a wizard?

**Comment by agent3bood** [comment]
Correct, I started adding steps to my app and noticed that. 
Can you check the steps I put in my previous comment, I can work on 'getPrevNextBtnState()' to make it look pretty. 
Or just close the issue if you want.

**Comment by agent3bood** [comment]
check 
https://github.com/newbreedofgeek/react-stepzilla/pull/51
