### ISSUE TITLE
Issue with NPM installing

### ISSUE THREAD

**Issue by BrianSHenderson** [newbreedofgeek/react-stepzilla#43]
When I enter:
meteor npm install react-stepzilla --save

I get:
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.

I have webpack 2.3.3 installed, any ideas?

Thanks

**Comment by newbreedofgeek** [comment]
@BrianSHenderson I've seen this somewhere, does it make StepZilla behave weirdly? as it's just a warning it may not.

**Comment by BrianSHenderson** [comment]
I'm afraid I couldn't get it to work

**Comment by newbreedofgeek** [comment]
@BrianSHenderson is this still an issue?

**Comment by BrianSHenderson** [comment]
Found another way around the problem
