### ISSUE TITLE
How to submit a form when clicking 'Next' button?

### ISSUE THREAD

**Issue by dsun29** [newbreedofgeek/react-stepzilla#5]
How to submit a form when clicking Next button? Or submit a form when clicking last Next button?

**Comment by newbreedofgeek** [comment]
Sorry for the very late reply @dsun29 .

I've updated the example to show you how you can handle the Save/Submit. Usually you do the save in the "one before last" step which is usually the "Review" step. The final step should be your "Thank you for saving step".

Here is the code change, I've commented the relevant React component with what is happening:
https://github.com/newbreedofgeek/react-stepzilla/commit/9354263c02ed68516f53507933f6fa8ba8737094
