### ISSUE TITLE
When starting at the second to last step 'next' does not render

### ISSUE THREAD

**Issue by agent3bood** [newbreedofgeek/react-stepzilla#50]
Hi 

I have four steps and when I set startAtStep={2}, the next button does not show up.
then I hit previous and every thing works fine.

**Comment by agent3bood** [comment]
check 
https://github.com/newbreedofgeek/react-stepzilla/pull/51

**Comment by newbreedofgeek** [comment]
Fixed in v4.6.0 via pull request #51 thanks to @agent3bood .

It's been tested but pease test and let us know if it has issues and we will reopen to investigate.
