### ISSUE TITLE
Able to Skip past Validation Steps

### ISSUE THREAD

**Issue by stevecawdery** [newbreedofgeek/react-stepzilla#6]
I noticed I can skip right to Step 4 from the overhead step options, even though Step 2 (let's take it from the example) requires form input - if I'm on step 2 it works fine, but if i'm on step 1 or 3 i can skip through. Is there a simple way to solve this?

**Comment by newbreedofgeek** [comment]
mmm.. this may be a bug. Let me have a look today.

**Comment by newbreedofgeek** [comment]
@stevecawdery it was indeed a bug, thanks for raising this.

I have redone most of the logic relating to validation control when enabled via `showNavigation: true` and `stepsNavigation: true`

This will now prevent the user from jumping into a step ahead when a step in between has not been validated. But it will let them jump backwards.

Let me know how you go.

Also, I completely rewrote the example app :) it looks better and is completely completely now.

**Comment by newbreedofgeek** [comment]
I've added a live working example https://newbreedofgeek.github.io/react-stepzilla/
