### ISSUE TITLE
Can we customize the steps progress?

### ISSUE THREAD

**Issue by JoaoCnh** [newbreedofgeek/react-stepzilla#64]
How can we customize the progress steps? I don't want the <em /> and <span /> approach.

How can this be done?

EDIT: Maybe even customize just the text of the em tag. I want a representative icon and not a number for example

**Comment by zeel** [comment]
we can take `stepRenderer` function as a prop and can use current one as default prop. 

cc: @newbreedofgeek

**Comment by newbreedofgeek** [comment]
Sorry for the delay in responding, this might help #113 

FontAwesomeIcon is used to customise the progress.
