### ISSUE TITLE
does this work with react native 

### ISSUE THREAD

**Issue by shaksi** [newbreedofgeek/react-stepzilla#66]
currently trying to figure out what react native multiform to use and I was wondering are there any issues that would hinder me using it in a native app? (Apologies if it is an ignorant question)

**Comment by newbreedofgeek** [comment]
@shaksi Sorry for the last reply and thanks for the question.

It Probably does not work as ReactNative has its own markup. i.e. <div> wont work (... has this changed, I have not worked with ReactNative for many months now?).

You can give it a go and let us know. Unfortunately we don't have any immediate plans to get this working on mobile. I will re-open this issue if we do and let you know.
