### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by aaronfranco** [newbreedofgeek/react-stepzilla#7]
There is no "dist" folder in the NPM package so the module can't be used in a project.

**Comment by newbreedofgeek** [comment]
@aaronfranco tnx for raising this. Did an upgrade 2 days ago... this bug slipped in, fixing now.

**Comment by newbreedofgeek** [comment]
@aaronfranco fixed now. npm update and it will now work. tnx!

**Comment by newbreedofgeek** [comment]
I've also added a link working example: https://newbreedofgeek.github.io/react-stepzilla/
