### ISSUE TITLE
What a breath of fresh air.

### ISSUE THREAD

**Issue by ensemblebd** [newbreedofgeek/react-stepzilla#76]
Thank your for this package. And for maintaining it. very impressed, thank you!!

**Comment by newbreedofgeek** [comment]
Thanks you. @zeel has been doing a great job.

**Comment by zeel** [comment]
Thank you @newbreedofgeek. I am happy to help. I am very excited to contribute to open source as much as I can. Let me know if anything new needs to be done.

**Comment by newbreedofgeek** [comment]
@rickgvs as mentioned in #90, its not on our todo at the moment. But please fork and attempt, and we can promote your project as an alternate.
