### ISSUE TITLE
Async step validation

### ISSUE THREAD

**Issue by jorgecuesta** [newbreedofgeek/react-stepzilla#8]
Hi, first of all, great work. I start to use it and let more easy my life ;)

I need to make some validation with backend service in step component. What should I return on validated method ? maybe you can support a Promise.

**Comment by newbreedofgeek** [comment]
@jorgecuesta tnx. Glad you find this useful.

Yes I agree, the validation should support aync validation as well.

At the moment is only support sync validation. You return "true" to indicate that its valid and "false" if its not valid. Not returning anything (i.e. undefined) is treated as "true". The logic is here:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js#L170

Let me convert this request to a "enhancement" and see if I can upgrade it to support a Promise.

If you want to give it a go as well, please do and submit a Pull Request :)

**Comment by newbreedofgeek** [comment]
@jorgecuesta I've updated the validation to support Promises :)

Here is how you can use it:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Step3.js#L22

It's in version 4.0.0 so make sure you `npm update`

**Comment by jorgecuesta** [comment]
Thanks @newbreedofgeek by the quick solution 👍

**Comment by jorgecuesta** [comment]
One note about async validation. Usually reject is used to handle wrong path like invalid state or error response.
I think the it should be resolve() for valid state and reject() for invalid state. 
You don't  really need a boolean value.

**Comment by newbreedofgeek** [comment]
Agree, I didn't use reject() due to a composability issue I had. But it is the right way to return false in this instance. Reopening this, I'll take a look when I have some time.

**Comment by newbreedofgeek** [comment]
@jorgecuesta it now supports resolve() and reject() correctly. Please try and let me know if any issues.

**Comment by jorgecuesta** [comment]
@newbreedofgeek Thanks again! you became my hero! 👍  
Now I wanna ask you if have a way to set Next button as disabled before component report a right validation state. 
If you want I can open a new issue and can tag it as enhancement.

**Comment by newbreedofgeek** [comment]
Yes @jorgecuesta , pls open a new issue as a enhancement.
