### ISSUE TITLE
Change last step to green checkbox on confirmation?

### ISSUE THREAD

**Issue by gtwilliams03** [newbreedofgeek/react-stepzilla#81]
My last step, like your demo, thanks the user for their submission after they have walked through the steps.  The convention on the UI steps seems to be confusing our users (the gray circle at the end seems to indicate something else needs to be done - is it possible to force the last step to be a green checkbox?

It seems like the last "thank you step" should show all green checkboxes (I even just tried `return true` in the last step's `isValidated()` function but that didn't seem to help.

![image](https://user-images.githubusercontent.com/1564628/36053983-0cf1aa34-0dc2-11e8-850f-149e6b1dc8e9.png)

**Comment by NomNomCameron** [comment]
+1

**Comment by newbreedofgeek** [comment]
@zeel this can be done with just a CSS update right?

@gtwilliams03 sorry for the delay in response, did you manage to solve it? have your tried custom CSS?

**Comment by newbreedofgeek** [comment]
tnx @zeel I will have a look today.

**Comment by newbreedofgeek** [comment]
@gtwilliams03 @NomNomCameron You can use this pure css solution so you are not blocked:
https://github.com/newbreedofgeek/react-stepzilla/blob/2862f1b8eb1436a1142ee670eeb646a942f4f6af/src/css/main.css#L98-L120

@zeel and I are working on the ideal solution

**Comment by gtwilliams03** [comment]
Thanks for the update!  I was working on another project - so sorry for the delay.  This isn't a huge issue for our project so I had just left the non-success icon on the last step for now (project is still in beta so it's not critical yet - but something our test users raised as confusing).

**Comment by newbreedofgeek** [comment]
@gtwilliams03 glad it was not a major blocker... see the CSS above, it will solve your issue.

**Comment by gtwilliams03** [comment]
@newbreedofgeek It did - thank you!

**Comment by zeel** [comment]
@newbreedofgeek I have updated PR with the fix. Please check once.

**Comment by newbreedofgeek** [comment]
fixed in #94 - thanks @zeel
