### ISSUE TITLE
Element type is invalid (Issue using with create-react-app)

### ISSUE THREAD

**Issue by mcnally** [newbreedofgeek/react-stepzilla#83]
Using a very basic example, directly after creating the app, results in this error

#### Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Here is how i used it
````
import React, { Component } from "react";
import StepZilla from "react-stepzilla";

const steps = [
  {
    name: "Step 1",
    component: <Step1 />
  }
];

const Step1 = props => {
  return (
    <div>
      <div>Step 1</div>
    </div>
  );
};
class App extends Component {
  render() {
    return (
      <div className="step-progress">
        <StepZilla steps={steps} />
      </div>
    );
  }
}

export default App;
````

**Comment by local-joke** [comment]
had similar issue. fixed it by movie the initialization of 'steps' inside the render function

**Comment by shakealot** [comment]
Face the same issue with create-react-app, but my mistake was something else. I wrote
`
import { StepZilla } from "react-stepzilla";`
instead of
`
import StepZilla from "react-stepzilla";`

**Comment by newbreedofgeek** [comment]
@mcnally sorry for the delay in response.

I believe @local-joke 's recommendation will work, although I can't say why there is an issue with your code, it should work as well. 

Maybe your `const Step1` was not being hoisted to the top and therefore there was the undefined error. (just a guess)

Let me know if you solved this issue, i'll close this for now but feel free to reopen with any new findings
