### ISSUE TITLE
Reusing a component across multiple steps - state is duplicated

### ISSUE THREAD

**Issue by realdubb** [newbreedofgeek/react-stepzilla#85]
Whenever I reuse a component across multiple steps they end up sharing the state. 

Check out the issue in this example: https://codesandbox.io/s/3ry507v6zm
Steps 2/3 - are using the same component, you can see the state is the same

I'm planning to create steps dynamically, utilizing the same component. I was thinking each step would maintain its own state.

What am I doing wrong? is this expected? Issue with the way I'm using React or Stepzilla?

**Comment by newbreedofgeek** [comment]
@realdubb I do clone the component before render [see here](https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js#L312) but this happens just before the render so I'm guessing its clones the state as well.

Try cloning it during StepZilla init. i.e. [here](https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Example.js#L41-L48)

React Clone - https://zhenyong.github.io/react/docs/top-level-api.html#react.cloneelement

**Comment by newbreedofgeek** [comment]
Closing as no response from OP - please re-open if you want to continue the discussion.
