### ISSUE TITLE
Preventing user jumping back a step? with nav bar enabled

### ISSUE THREAD

**Issue by johnantoni** [newbreedofgeek/react-stepzilla#86]
Hi,

With the navigation enabled is there any way of preventing user's jumping back to previous steps?

**Comment by newbreedofgeek** [comment]
@johnantoni Sorry, I dont follow. Do you mean you want to prevent users jumping back steps from the header steps? i.e. you enable `stepsNavigation` but only want to make users for 'front' not back?

**Comment by johnantoni** [comment]
@newbreedofgeek yep, as in show the navigation steps (1 --- 2 --- 3 --- 4) but not allow them to jump back to previous steps.

**Comment by newbreedofgeek** [comment]
@johnantoni as per documentation, have you tried:

```
// disable or enable onClick step jumping from the UI navigation on top
stepsNavigation: true | false
```

Does this suit your need?

**Comment by johnantoni** [comment]
that'll do thanks
