### ISSUE TITLE
Unable to load the icons for react-stepzilla

### ISSUE THREAD

**Issue by sabun123** [newbreedofgeek/react-stepzilla#87]
I'm getting 404's when trying to run this. It looks like it's pointing to a dead link:
https://newbreedofgeek.github.io/favicon.ico

Is there an alternative or a quick fix for this?
My UI is ending up looking like the following currently:
![bugger](https://user-images.githubusercontent.com/3523483/37027187-9a27c962-216b-11e8-8a15-b1c5b03937bd.png)

I'd like to achieve the look like in the following screenshot:
![ref](https://user-images.githubusercontent.com/3523483/37027216-b2ce7952-216b-11e8-9685-78c77db24fb0.png)

Any tips? Much appreciated.

**Comment by Adamkzh** [comment]
you need add .css file

**Comment by sabun123** [comment]
Thanks for the response, where do I get this .css file from? I figured it would have been included during the npm install process.
