### ISSUE TITLE
Adding onclick event on "next" button

### ISSUE THREAD

**Issue by Adamkzh** [newbreedofgeek/react-stepzilla#88]
Hi,
Is there any open api for adding onclick function when click "next" button?  Or any other ways to helping with this problem ?
I want to record the input and doing a screenshot when click "next".

**Comment by newbreedofgeek** [comment]
@Adamkzh yes, you can tap into the isValidated() method which prevents moving front until certain conditions are met. [Step Validation](https://github.com/newbreedofgeek/react-stepzilla#step-validation)

Check out an example here : [Step 5](https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Step5.js)

**Comment by newbreedofgeek** [comment]
@Adamkzh closing for now, pls reopen if you have any other requirement and provide a example of what you are trying to do.
