### ISSUE TITLE
add typings file 

### ISSUE THREAD

**Issue by rickgvs** [newbreedofgeek/react-stepzilla#90]
It is a shame your library doesnt have a typings file 
we are in 2018 people use typescript, you can make a typings file in a bit and publish it will ya.
hehehe actually I think your library is super awesome and I feel a little frustrated that I cannot run it in this typescript portal I am doing.

**Comment by newbreedofgeek** [comment]
@rickgvs :) thanks for the comment. Would love to spin off a TypeScript version of this, but not on our todo list at the moment. You can fork this and make it TypeScript compliant, pls share the link if you do so we can keep track of your project and promote it for plp wanting a TypeScript version.

**Comment by malafreniere** [comment]
For anyone interested in a definition file to support typescript, here's a simple one:

```typescript
// react-stepzilla.d.ts
declare module "react-stepzilla" {
    export interface IStep {
        name: string | JSX.Element;
        component: JSX.Element;
    }

    export interface IStepZillaProps {
        steps: IStep[];
        showSteps?: boolean;
        showNavigation?: boolean;
        stepsNavigation?: boolean;
        prevBtnOnLastStep?: boolean;
        dontValidate?: boolean;
        preventEnterSubmission?: boolean;
        startAtStep?: number;
        nextButtonText?: string | JSX.Element;
        nextTextOnFinalActionStep?: string | JSX.Element;
        nextButtonCls?: string;
        backButtonCls?: string;
        backButtonText?: string | JSX.Element;
        hocValidationAppliedTo?: number[],
        onStepChange?: (step: number) => void;
    }

    export default class StepZilla extends React.Component<IStepZillaProps, {}> {} 
}
```

**Comment by spearconsult** [comment]
Hi, please advise,

I added the definition file in a 'types' folder under 'src'. 
I used the regular 'npm install --save ...' method to add the module to the project. 
I Added **import { StepZilla2 } from 'react-stepzilla';** to the beginning of the tsx file where I want to add the 'StepZilla' component.

When I remove the component from the page, there is no error, but when I try to use it, two errors show up with the following messages:

**Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `MainComponent`.

Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `MainComponent`.**

After changing name of the module 'react-stepzilla' in the declaration to 'react-stepzilla2', there was no change. This seems odd to me.
After changing  the class name to 'StepZilla2', I was forced to change it in the import and on the component as wel. This seems that it is correctly using the definition file.

Somehow I get the impression that the definition file has no link to the module at all.

What am I missing here?

Cheers,
Erik

**Comment by AlluManikyam** [comment]
You can import the  stepzilla like this 

import StepZilla2 from 'react-stepzilla'  instead of  import { StepZilla2 } from 'react-stepzilla';

**Comment by riyadshauk** [comment]
Thanks @malafreniere for the *.d.ts file. I was having problems with that exact file. After some trial/error, here's a minimal set-up that works with me (transpiles, works fine in the VS Code IDE):

```typescript
// my-wizard-component-dir/react-stepzilla.d.ts
declare module 'react-stepzilla' {
  import { Component } from 'react';

  export interface IStep {
      name: string;
      component: JSX.Element;
  }

  export interface IStepZillaProps {
      steps: IStep[];
      showSteps?: boolean;
      showNavigation?: boolean;
      stepsNavigation?: boolean;
      prevBtnOnLastStep?: boolean;
      dontValidate?: boolean;
      preventEnterSubmission?: boolean;
      startAtStep?: number;
      nextButtonText?: string;
      nextTextOnFinalActionStep?: string;
      nextButtonCls?: string;
      backButtonCls?: string;
      backButtonText?: string;
      hocValidationAppliedTo?: number[],
      onStepChange?: (step: number) => void;
  }

  // eslint-disable-next-line react/prefer-stateless-function
  export default class StepZilla extends Component<IStepZillaProps, {}> {}
}
```

```javascript
// my-wizard-component-dir/react-stepzilla.js
import StepZilla from 'react-stepzilla';

export default StepZilla;
```

```typescript
// my-wizard-component-dir/Wizard.ts
import React from 'react';
import StepZilla from 'react-stepzilla';
import Step1 from './Step1';
import Step2 from './Step2';
import Step3 from './Step3';

export default () => {
  const steps = [
    { name: 'Step 1', component: <Step1 /> },
    { name: 'Step 2', component: <Step2 /> },
    { name: 'Step 3', component: <Step3 /> },
  ];
  return (
    <div className="step-progress">
      <StepZilla steps={steps} />
    </div>
  );
};
```

I'm not a pro with TypeScript, so I had to search around and figure out how to get it all to work together. This SO link helped me get there: https://stackoverflow.com/questions/42693836/typescript-custom-declaration-files-for-untyped-npm-modules .
