### ISSUE TITLE
Defining the port number

### ISSUE THREAD

**Issue by JimiPedros** [newbreedofgeek/react-stepzilla#95]
Hi there

This is not so much an issue, but more a question; how can I define the port number in stepzilla source? 

I would like to change it to port no. 80 

Thanks in adv.

**Comment by newbreedofgeek** [comment]
@JimiPedros we use the default `webpack-dev-server` to launch the `example` step. By default it uses 8080, I'm sure you can specify the port number by update the package.json `example` script to specify the port. Check out the webpack-dev-server docs... 

Please report back if you solve the issue in case other user need to do the same in future...

**Comment by newbreedofgeek** [comment]
Closing this issue for now, please re-open if its a bug. Tnx @JimiPedros
